version: '3.8'
services:
  sit_profile_analizer_client:
    container_name: sit_profile_analizer_web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
